language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CMAKE_FLAGS="" DEPLOY_DOCS="yes"
  - CMAKE_FLAGS="-DTINYSPLINE_FLOAT_PRECISION=yes"
  - CMAKE_FLAGS="-DTINYSPLINE_DISABLE_CXX11_FEATURES=yes"

osx_image: xcode9.2

dist: xenial

sudo: true

install:
  - pushd ci
  - ./install_debs.sh
  - popd

before_script:
  - export BUILD_DIR="build"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CMAKE_FLAGS="$CMAKE_FLAGS -DTINYSPLINE_WITH_PHP=FALSE -DTINYSPLINE_WITH_RUBY=FALSE"; fi;

script:
  - pushd ci
  - ./compile.sh
  - ./deploy_docs.sh
  - popd
