version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pushd ci && ./install_debs.sh && popd
      - run:
          name: Print the Current Time
          command: date
