version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pushd ci && ./install_debs.sh && popd
      - run:
          name: Compile Code
          command: pushd ci && BUILD_DIR=build ./compile.sh && popd
